version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "SuaSenhaForteAqui123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"$${SA_PASSWORD}\" -Q \"SELECT 1\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12

  transacoes-api:
    build:
      context: .
      dockerfile: Transacoes/Dockerfile
    container_name: transacoes-api
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=FinanceiroDb;User Id=sa;Password=SuaSenhaForteAqui123!;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5002:8080"
    depends_on:
      - sqlserver

volumes:
  sqlserver-data: